// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV-7G0JK2iZLNQRztHcyrlLztUhK-4sFY',
    appId: '1:503246556065:web:946e1fdf5db2583e0d99e0',
    messagingSenderId: '503246556065',
    projectId: 'mailer-4f803',
    authDomain: 'mailer-4f803.firebaseapp.com',
    storageBucket: 'mailer-4f803.appspot.com',
    measurementId: 'G-M7PRENMX94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkBRuPMNfyG0virC5EmuZOKyvd412aosA',
    appId: '1:503246556065:android:fe1d11bc8ae40a1e0d99e0',
    messagingSenderId: '503246556065',
    projectId: 'mailer-4f803',
    storageBucket: 'mailer-4f803.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMS7jHoyjLjm_8_GRToHfk19-cQCpW-So',
    appId: '1:503246556065:ios:659115305238c79f0d99e0',
    messagingSenderId: '503246556065',
    projectId: 'mailer-4f803',
    storageBucket: 'mailer-4f803.appspot.com',
    iosBundleId: 'com.example.mailer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMS7jHoyjLjm_8_GRToHfk19-cQCpW-So',
    appId: '1:503246556065:ios:659115305238c79f0d99e0',
    messagingSenderId: '503246556065',
    projectId: 'mailer-4f803',
    storageBucket: 'mailer-4f803.appspot.com',
    iosBundleId: 'com.example.mailer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV-7G0JK2iZLNQRztHcyrlLztUhK-4sFY',
    appId: '1:503246556065:web:53cb76c92a4ed8f60d99e0',
    messagingSenderId: '503246556065',
    projectId: 'mailer-4f803',
    authDomain: 'mailer-4f803.firebaseapp.com',
    storageBucket: 'mailer-4f803.appspot.com',
    measurementId: 'G-BFRJYWNMQJ',
  );
}
